services:
  postgres:
    build: .
    container_name: cubesat_monitoring
    environment:
      POSTGRES_DB: cubesat_db
      POSTGRES_USER: cubesat_user
      POSTGRES_PASSWORD: cubesat_pass
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./backup:/backup
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U cubesat_user -d cubesat_db"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data: